### PR TITLE
Remove unused code, fix invalid memory access

### PR DESCRIPTION
**Pull request by mardy**
It's easier to review this commit by commit.

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
Looks like the build ended up in a really strange state due to branch naming. @mardy, could you push these commits to a branch in this repository for testing?

**Comment by mardy** [comment]
Pushed as https://github.com/ubports/qtorganizer5-eds/tree/xenial_-_tmp-remove-unused-code

**Review by hummlbach — COMMENTED** [review]
Review of the first commit. We do not override:

- `removeItems(const QList<QOrganizerItem> *, ...)`
- `managerParameters`
- and `idInterpretationParameters`

I guess thats okay?

**Review by hummlbach — APPROVED** [review]
Had a short look over the commits. Lets merge :)

**Pull request merged**
