### PR TITLE
Make sure QDateTime is valid

### PR DESCRIPTION
**Pull request by mariogrip**
Fixes https://github.com/ubports/ubuntu-touch/issues/705

### CODE REVIEW

**Comment by mariogrip** [comment]
Hold on with this, dont merge yet

**Review by NeoTheThird — APPROVED** [review]

**Comment by NeoTheThird** [comment]
What's wrong?

**Comment by mariogrip** [comment]
this fixes the crash, but the times are not there, it just says 00:00 times on alarms

**Comment by NeoTheThird** [comment]
oh dammit, you are right

**Review by NeoTheThird — CHANGES_REQUESTED** [review]
dis broken

**Review by NeoTheThird — APPROVED** [review]
works, gj

**Pull request merged**
